#!/usr/bin/env python3
"""Emit Z80 DB lines for a minimal Spectrum BASIC loader (zmakebas memory layout)."""
# Line record: MSB lineno, LSB lineno, len_lo, len_hi, body..., 0x0D
# Numbers: ASCII digits + 0x0E + exp + 4 mantissa bytes (zmakebas dbl2spec int path)


def speccy_inline_num(n: int) -> bytes:
    tmp = abs(int(n))
    if tmp > 65535:
        raise ValueError(n)
    exp = 0
    man = ((tmp % 256) << 16) | ((tmp >> 8) << 8)
    man &= 0x7FFFFFFF
    digits = str(tmp).encode("ascii")
    return digits + bytes([0x0E, exp & 0xFF, (man >> 24) & 0xFF, (man >> 16) & 0xFF, (man >> 8) & 0xFF, man & 0xFF])


def line(lineno: int, body: bytes) -> bytes:
    if not body.endswith(b"\x0d"):
        body = body + b"\x0d"
    ln = len(body)
    return bytes([lineno >> 8, lineno & 0xFF, ln & 0xFF, (ln >> 8) & 0xFF]) + body


def db_lines(data: bytes, per_line: int = 16) -> str:
    out = []
    for i in range(0, len(data), per_line):
        chunk = data[i : i + per_line]
        parts = ", ".join(f"#{b:02x}" for b in chunk)
        out.append(f"    DB {parts}")
    return "\n".join(out)


def main() -> None:
    # Tokens: CLEAR #FD, LOAD #EF, CODE #AF, RANDOMIZE #F9, USR #C0
    l10 = bytes([0xFD]) + speccy_inline_num(32767)
    l20 = bytes([0xEF, 0x22, 0x22, 0xAF])
    l30 = bytes([0xF9, 0x20, 0xC0]) + speccy_inline_num(32768)

    prog = line(10, l10) + line(20, l20) + line(30, l30)
    print("; Auto-generated by tools/gen_loader.py — do not edit")
    print("LoaderBasic:")
    print(db_lines(prog))
    print("LoaderBasicEnd:")


if __name__ == "__main__":
    main()
